# Generated by Django 5.2.4 on 2025-07-31 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_apiuser_groups_apiuser_is_active_apiuser_is_staff_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apiuser',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='apiuser',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='apiuser',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='apiuser',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='apiuser',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='apiuser',
            name='user_permissions',
        ),
        migrations.AlterField(
            model_name='apiuser',
            name='password',
            field=models.CharField(max_length=128),
        ),
    ]
